---
name: Integration Test

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  issues: read
  pull-requests: read

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Integration test
        run: bash scripts/integration-test.sh
